name = "Forged Extraction"
author = "oygurd"
version = "1.1.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8f87ec75f2a7eec40d0b33dceb965c5855104c86fd20aae4ad2138fe63dd63b"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
